fieldLayouts:
  2b9c7d28-9188-4b33-812c-932cd13f32ca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f94ada10-c416-4cbe-bfd7-e23a1e96dd67
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 736e7c2a-c6c7-4609-b1f2-38e7709e56cf # Teaser Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7d3682e-07e2-4e62-90a3-45afa6802033
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cf2dac30-56a5-4a12-91a4-ed35d2eed4ab # Teaser Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73667ecd-a3c3-4737-9032-a86e4063c2c9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f4696807-fad3-4e93-a26a-e1946637d383 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c29b0c67-40d9-46d8-8949-a09373f7b207
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b72c1e8b-f22a-42b5-846d-8314c08dd793 # Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aaf55c98-7e94-40db-9826-0a3c5509ce9a
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: 83f2dfe0-dfb9-4c3f-99d9-9cabfbbae03e
        userCondition: null
handle: blog_default
hasTitleField: true
name: Default
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 0
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
