fieldLayouts:
  fa1fa13e-dfac-40f6-8fe5-5066b6e2510f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e08268fc-f65b-4064-9090-95cba96995f5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f4696807-fad3-4e93-a26a-e1946637d383 # Body
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15f52edd-0eb1-4199-9500-7c65bbbd7368
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 087761ad-d0fe-4569-8140-0e379ef60d8a
        userCondition: null
handle: homepage
hasTitleField: true
name: Homepage
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 0
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
