color: null
description: null
fieldLayouts:
  6fc4afe9-a01f-45bf-a9cd-ce8b713d8d40:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: bc8a2715-5172-471b-8357-589ba0ab3209
            handle: null
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0cfd0ce-1a0b-489e-be75-3960a4eb6f11
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 1beade96-c14b-406a-896b-e052a13ec594
            handle: null
            includeInCards: true
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e247ab9-92a6-4bc6-99fe-2a038ab5f324
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 942db2b2-2993-4398-95a5-fa14532c58d0
            handle: null
            includeInCards: false
            instructions: null
            label: Layout
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8865a55-963e-4f77-a511-de2a756a159a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 73307f61-5a82-43e2-95ec-8aef611b6250
        userCondition: null
handle: image
hasTitleField: false
icon: null
name: Image
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
