fieldLayouts:
  e400c5e4-326e-47e1-9074-cc4a1de24b82:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'Review Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6657245d-095b-40c5-91d2-5336d056c16a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f4696807-fad3-4e93-a26a-e1946637d383 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e9c6329-db69-4138-a105-3ac1f1d711a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6f055d5e-e5e3-4363-81de-c7dff55ad3b3 # Book ASIN
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a471e50-0b5e-4c67-ab07-ffd0ec1d5e15
            userCondition: null
            warning: null
            width: 100
        name: 'Review Content'
        uid: e31512b7-e3da-4373-a1ac-cea66e050c81
        userCondition: null
handle: review_default
hasTitleField: true
name: Default
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 0
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
