color: null
description: null
fieldLayouts:
  ae2817ec-1083-4a4d-b4bb-0a2d71acac2c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: c5a9f115-5b57-497d-9a9f-c76ef6a8881e
            handle: null
            includeInCards: true
            instructions: null
            label: Content
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92324ac7-d875-4c11-89cc-252044a9085a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 25a4f662-835a-401a-a147-f2efdc644295
        userCondition: null
handle: text
hasTitleField: false
icon: null
name: Text
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
