fieldLayouts:
  48315f31-0ea0-44ad-a10e-31db5ffb0cf0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: fa41ce2f-444e-4278-9f7f-09763df8486a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3361eaed-26eb-48ba-afb5-7a871e8d16d6
        userCondition: null
fs: podcastEpisodes
handle: podcastEpisodes
name: 'Podcast Episodes'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
