columnSuffix: null
contentColumnType: string
handle: body
instructions: null
name: Body
searchable: true
settings:
  entryTypes:
    -
      uid: 39b7122f-8343-4bfd-ba42-51db49838e4a
    -
      uid: 67031931-0155-4204-8483-32624008ae23
    -
      uid: 67470af9-2f4e-4aac-b68c-d4c787c163e4
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
