columnSuffix: null
contentColumnType: text
handle: bookASIN
instructions: 'The ASIN from Amazon.com for this book. Your affiliate ID will be automatically included in the URL. '
name: 'Book ASIN'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
