columnSuffix: null
handle: layout
instructions: null
name: 'Body - Image - Layout'
searchable: true
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - left
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - right
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Full
        -
          - value
          - full
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
