columnSuffix: null
contentColumnType: string
handle: tags
instructions: null
name: Tags
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'taggroup:237da2ff-504f-4e2c-bf6c-152bf831c8f1' # Default
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Tags
