dateModified: 1762630344
email:
  fromEmail: ryan@mijingo.com
  fromName: Downlink
  template: null
  transportType: craft\mail\transportadapters\Sendmail
fs:
  blogImages:
    hasUrls: true
    name: 'Blog Images'
    settings:
      cdnUrlPattern: ''
      customSubfolder: blog-images
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://cdn2.assets-servd.host/'
  podcastEpisodes:
    hasUrls: true
    name: 'Podcast Episodes'
    settings:
      cdnUrlPattern: ''
      customSubfolder: podcast-episodes
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://cdn2.assets-servd.host/'
  userPhotos:
    hasUrls: true
    name: 'User Photos'
    settings:
      cdnUrlPattern: ''
      customSubfolder: user-photos
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://cdn2.assets-servd.host/'
meta:
  __names__:
    1bf5de18-32cf-4854-ad4e-b7d9014dcf02: 'User Photos' # User Photos
    7c831f23-da90-4f0d-90a2-454375ee2e8e: 'Podcast Episodes' # Podcast Episodes
    33c8318a-f8ad-43f7-8231-448c204a6ed9: 'Blog Images' # Blog Images
plugins:
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.14.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      assetsEnvironment: ''
      assetsEnvironmentOverwrite: ''
      cacheClearMode: full
      clearCachesOnSave: always
      disableDynamic: ''
      disableTransforms: ''
      injectCors: '1'
      projectSlug: $SERVD_PROJECT_SLUG
      securityKey: $SERVD_SECURITY_KEY
      suppressWarnings: '1'
      useLocalVolumes: ''
system:
  edition: pro
  live: true
  name: Downlink
  schemaVersion: 4.15.0.0
  timeZone: UTC
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
