defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: a95fdc3d-b143-489a-8ee7-22ae7268c278 # Default
  -
    uid: c1d8279b-ea8f-4690-9ecf-97c82d6f64ca # Link
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  35c13b6c-aaee-499a-9580-96963583b7f4: # Downlink (en-US)
    enabledByDefault: true
    hasUrls: true
    template: entry
    uriFormat: 'blog/{postDate|date("Y")}/{postDate|date("m")}/{slug}'
type: channel
