defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5610066d-2f20-4444-a547-eb560bda26a5 # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  35c13b6c-aaee-499a-9580-96963583b7f4: # Downlink (en-US)
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
